version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./scrape-apartments-front
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: ./scrape-apartments
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

volumes:
  db:
    driver: local